### ISSUE TITLE
UM S3 cannot be reached through hostname

### ISSUE THREAD

**Issue by reinvantveer** [Ultimaker/um-kernel#192]
Not sure where to report this (it's definitely not a Cura issue).
I can retrieve the hostname for my S3, but it doesn't respond on that hostname:

```
$ curl -X GET --header 'Accept: application/json' 'http://192.168.20.106/api/v1/system/hostname'
"ultimakersystem-dc73a76132ca454d8f7788e22c92cd5c"
$ curl -X GET --header 'Accept: application/json' 'http://ultimakersystem-dc73a76132ca454d8f7788e22c92cd5c/api/v1/system/hostname'
curl: (6) Could not resolve host: ultimakersystem-dc73a76132ca454d8f7788e22c92cd5c
```
How can I reach the S3 by its hostname?
I have firmware v8.3.1

Thank you.

**Comment by sj3fk3** [comment]
Resolving something by name requires a resolver (either dns or mdns). For instance: If you would put the hostname in your /etc/host file on the system where you type the curl command, it would work just fine. If your network supports mdns using the fqdn hostname.local might also work.

**Comment by reinvantveer** [comment]
Aha I can now solve my own question. As far as I can tell, there's only one tool that was able to tell me the network hostname for my Ultimaker:
```
$ avahi-resolve -a 192.168.20.106
192.168.20.106	ultimakersystem-dc73a76132ca454d8f7788e22c92cd5c.local
```
